# Generated by Django 6.0.7 on 2026-07-29 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APICHAT', '0003_generatedimage_action_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='action',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='action',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
